from pathlib import Path

def rep(s, old, new, name):
    if old not in s: raise SystemExit(f'missing {name}')
    return s.replace(old,new,1)

# Psoriasis: distinct generic WhatsApp CTA + English summaries for each substantive section.
p=Path('psoriasis-treatment.html'); s=p.read_text()
s=rep(s,'<a class="cta call" data-specialty="dermatology" data-service="psoriasis" href="tel:+962778423361">اتصل بالعيادة</a></div>','<a class="cta call" data-specialty="dermatology" data-service="psoriasis" href="tel:+962778423361">اتصل بالعيادة</a><a class="cta outline" data-specialty="dermatology" data-service="psoriasis" href="https://wa.me/962778423361" target="_blank" rel="noopener">تواصل عبر واتساب | WhatsApp</a></div>','psoriasis CTA')
s=rep(s,'<section class="card"><h2>أشكال شائعة للصدفية</h2><div class="grid">','<section class="card"><h2>أشكال شائعة للصدفية</h2><p class="en">Common presentations include plaque, scalp, inverse, guttate and nail psoriasis. Pustular or very widespread inflammatory forms are less common and may require faster assessment depending on symptoms.</p><div class="grid">','psoriasis types English')
s=rep(s,'<section class="card"><h2>متى تحتاج إلى تقييم طبيب جلدية؟</h2><p>يُنصح بالتقييم عندما تكون البقع جديدة أو غير مؤكدة التشخيص، واسعة أو مزعجة، تؤثر على النوم أو العمل، تصيب الوجه أو الأعضاء التناسلية أو اليدين والقدمين، تترافق مع تغيرات الأظافر، أو عندما تكون العلاجات السابقة غير كافية. الألم أو التيبس أو التورم في المفاصل يجب ذكره للطبيب.</p></section>','<section class="card"><h2>متى تحتاج إلى تقييم طبيب جلدية؟</h2><p>يُنصح بالتقييم عندما تكون البقع جديدة أو غير مؤكدة التشخيص، واسعة أو مزعجة، تؤثر على النوم أو العمل، تصيب الوجه أو الأعضاء التناسلية أو اليدين والقدمين، تترافق مع تغيرات الأظافر، أو عندما تكون العلاجات السابقة غير كافية. الألم أو التيبس أو التورم في المفاصل يجب ذكره للطبيب.</p><p class="en">Dermatologic assessment is useful when the diagnosis is uncertain, disease is extensive or troublesome, sensitive sites are involved, nail changes occur, previous treatment is insufficient, or joint pain, stiffness or swelling is present.</p></section>','psoriasis assessment English')
s=rep(s,'<section class="card"><h2>فئات علاج الصدفية</h2><p>تُختار خيارات العلاج بعد التقييم الجلدي وقد تشمل فئة واحدة أو أكثر. ذكر العلاج هنا لا يعني أن كل خيار يُقدّم داخل عيادات أوسارا؛ بعض الخيارات قد تحتاج وصفاً ومتابعة أو إحالة لمركز مناسب.</p>','<section class="card"><h2>فئات علاج الصدفية</h2><p>تُختار خيارات العلاج بعد التقييم الجلدي وقد تشمل فئة واحدة أو أكثر. ذكر العلاج هنا لا يعني أن كل خيار يُقدّم داخل عيادات أوسارا؛ بعض الخيارات قد تحتاج وصفاً ومتابعة أو إحالة لمركز مناسب.</p><p class="en">Treatment options are selected after dermatologic assessment and may include topical therapy, phototherapy, systemic medication or biologic treatment. Listing an option here does not mean every treatment is physically provided at OSara Clinics.</p>','psoriasis treatment English')
s=rep(s,'<section class="card"><h2>كيف يتم اختيار الخطة العلاجية؟</h2><p>لا توجد خطة واحدة مناسبة لكل المرضى.','<section class="card"><h2>كيف يتم اختيار الخطة العلاجية؟</h2><p>لا توجد خطة واحدة مناسبة لكل المرضى.','psoriasis plan anchor')
s=s.replace('<div class="note">الصدفية عادةً حالة طويلة الأمد يمكن السيطرة عليها بدرجات مختلفة. الهدف هو تقليل نشاط المرض والأعراض وتحسين جودة الحياة، وليس الوعد بـ«شفاء نهائي» أو نتيجة مضمونة.</div>','<p class="en">Treatment choice depends on disease extent and location, symptoms, nail or joint involvement, age, pregnancy considerations where relevant, other health conditions, previous therapy and patient preferences.</p><div class="note">الصدفية عادةً حالة طويلة الأمد يمكن السيطرة عليها بدرجات مختلفة. الهدف هو تقليل نشاط المرض والأعراض وتحسين جودة الحياة، وليس الوعد بـ«شفاء نهائي» أو نتيجة مضمونة.<br><span class="en">Psoriasis is usually a long-term condition. The goal is disease control and symptom improvement, not a guaranteed cure.</span></div>',1)
s=rep(s,'<section class="card"><h2>متى قد يكون التقييم عاجلاً؟</h2><p>اطلب تقييماً طبياً عاجلاً إذا أصبحت الصدفية واسعة جداً أو شديدة الاحمرار والألم، ظهرت بثرات منتشرة مع حرارة أو شعور عام بالتعب، حدث تدهور سريع، أو ظهرت أعراض مفصلية شديدة. الحالات الشديدة أو المهددة للحياة تستدعي التوجه إلى قسم الطوارئ المناسب.</p></section>','<section class="card"><h2>متى قد يكون التقييم عاجلاً؟</h2><p>اطلب تقييماً طبياً عاجلاً إذا أصبحت الصدفية واسعة جداً أو شديدة الاحمرار والألم، ظهرت بثرات منتشرة مع حرارة أو شعور عام بالتعب، حدث تدهور سريع، أو ظهرت أعراض مفصلية شديدة. الحالات الشديدة أو المهددة للحياة تستدعي التوجه إلى قسم الطوارئ المناسب.</p><p class="en">Seek urgent medical assessment for rapid widespread worsening, marked redness or pain, widespread pustules with fever or systemic illness, or severe joint symptoms. Severe or life-threatening illness belongs in the appropriate emergency department.</p></section>','psoriasis urgent English')
s=rep(s,'<section class="card"><h2>الاستشارة في عيادات أوسارا</h2><p>يمكن تقييم الحالة','<section class="card"><h2>الاستشارة في عيادات أوسارا</h2><p>يمكن تقييم الحالة','psoriasis consult anchor')
s=s.replace('</a>. يمكنك أيضاً العودة إلى <a href="/dermatology">صفحة الجلدية</a> أو قراءة <a href="/vitiligo-jordan">دليل البهاق</a> عند الحاجة.</p><div class="cta-row">','</a>. يمكنك أيضاً العودة إلى <a href="/dermatology">صفحة الجلدية</a> أو قراءة <a href="/vitiligo-jordan">دليل البهاق</a> عند الحاجة.</p><p class="en">Consultation focuses on confirming the diagnosis, assessing severity and discussing an appropriate next step rather than promising a specific treatment before examination.</p><div class="cta-row">',1)
p.write_text(s)

# Acne scars: distinct generic WhatsApp CTA + English summaries.
p=Path('acne-scar-treatment.html'); s=p.read_text()
s=rep(s,'<a class="cta call" data-specialty="dermatology" data-service="acne-scars" href="tel:+962778423361">اتصل بالعيادة</a></div>','<a class="cta call" data-specialty="dermatology" data-service="acne-scars" href="tel:+962778423361">اتصل بالعيادة</a><a class="cta outline" data-specialty="dermatology" data-service="acne-scars" href="https://wa.me/962778423361" target="_blank" rel="noopener">تواصل عبر واتساب | WhatsApp</a></div>','acne CTA')
s=rep(s,'<section class="card"><h2>أنواع ندبات حب الشباب</h2><div class="grid">','<section class="card"><h2>أنواع ندبات حب الشباب</h2><p class="en">Depressed acne scars are commonly described as rolling, boxcar or ice-pick scars. Raised hypertrophic or keloidal scars behave differently and require a different treatment strategy.</p><div class="grid">','acne types English')
s=rep(s,'<section class="card"><h2>لماذا لا يوجد علاج واحد لكل الندبات؟</h2><p>قد يجتمع أكثر من نوع من الندبات في الوجه نفسه. لذلك تُبنى الخطة على شكل الندبة وعمقها وقابليتها للشد، إضافة إلى لون البشرة وخطر التصبغ التالي للالتهاب. بعض الندبات تستفيد أكثر من تحرير التليف، وأخرى من معالجة سطحية أو موجهة، بينما قد تحتاج الحالات المختلطة إلى أكثر من إجراء على مراحل.</p></section>','<section class="card"><h2>لماذا لا يوجد علاج واحد لكل الندبات؟</h2><p>قد يجتمع أكثر من نوع من الندبات في الوجه نفسه. لذلك تُبنى الخطة على شكل الندبة وعمقها وقابليتها للشد، إضافة إلى لون البشرة وخطر التصبغ التالي للالتهاب. بعض الندبات تستفيد أكثر من تحرير التليف، وأخرى من معالجة سطحية أو موجهة، بينما قد تحتاج الحالات المختلطة إلى أكثر من إجراء على مراحل.</p><p class="en">A single face may contain several scar morphologies. Treatment is therefore based on scar depth, tethering, skin type and pigmentation risk rather than choosing one procedure for everyone.</p></section>','acne morphology English')
s=rep(s,'<section class="card"><h2>خيارات علاجية يمكن مناقشتها بعد التقييم</h2><p>الخيارات التالية فئات عامة في علاج ندبات حب الشباب. ذكر الإجراء لا يعني تلقائياً أنه مناسب لكل مريض أو متاح داخل العيادة في كل حالة؛ الاختيار يكون بعد الفحص.</p>','<section class="card"><h2>خيارات علاجية يمكن مناقشتها بعد التقييم</h2><p>الخيارات التالية فئات عامة في علاج ندبات حب الشباب. ذكر الإجراء لا يعني تلقائياً أنه مناسب لكل مريض أو متاح داخل العيادة في كل حالة؛ الاختيار يكون بعد الفحص.</p><p class="en">General options may include subcision, microneedling, focal chemical reconstruction such as TCA CROSS, other resurfacing approaches and combination treatment. Suitability and availability must be confirmed after examination.</p>','acne treatments English')
s=rep(s,'<section class="card"><h2>حب الشباب النشط أولاً</h2><p>إذا كان هناك حب شباب التهابي نشط، يجب تقييمه ضمن الخطة لأن ظهور آفات جديدة قد يؤدي إلى ندبات جديدة. في كثير من الحالات يكون ضبط النشاط الالتهابي جزءاً أساسياً قبل أو بالتوازي مع علاج الندبات.</p></section>','<section class="card"><h2>حب الشباب النشط أولاً</h2><p>إذا كان هناك حب شباب التهابي نشط، يجب تقييمه ضمن الخطة لأن ظهور آفات جديدة قد يؤدي إلى ندبات جديدة. في كثير من الحالات يكون ضبط النشاط الالتهابي جزءاً أساسياً قبل أو بالتوازي مع علاج الندبات.</p><p class="en">Active inflammatory acne should also be assessed because new lesions can create new scars. Controlling active disease is often part of scar planning.</p></section>','acne active English')
s=rep(s,'<section class="card"><h2>لون البشرة وخطر التصبغ</h2><p>خطة العلاج لا تعتمد على شكل الندبة فقط. البشرة الأكثر عرضة لفرط التصبغ التالي للالتهاب تحتاج اختياراً حذراً لنوع الإجراء وشدته، مع عناية مناسبة قبل وبعد الجلسات عند الحاجة. لهذا السبب لا يُنصح باختيار جلسة لمجرد أنها شائعة أو مناسبة لشخص آخر.</p></section>','<section class="card"><h2>لون البشرة وخطر التصبغ</h2><p>خطة العلاج لا تعتمد على شكل الندبة فقط. البشرة الأكثر عرضة لفرط التصبغ التالي للالتهاب تحتاج اختياراً حذراً لنوع الإجراء وشدته، مع عناية مناسبة قبل وبعد الجلسات عند الحاجة. لهذا السبب لا يُنصح باختيار جلسة لمجرد أنها شائعة أو مناسبة لشخص آخر.</p><p class="en">Skin type and post-inflammatory pigmentation risk influence procedure choice, intensity and aftercare. A treatment that suits one person may not suit another.</p></section>','acne pigment English')
s=s.replace('<div class="note">عدد الجلسات ونوعها والفاصل بينها لا يمكن تحديده بدقة قبل فحص نوع الندبات، الجلد وحب الشباب النشط.</div>','<p class="en">Realistic treatment aims to make scars less noticeable and improve texture. Multiple sessions or staged combination treatment are often considered; complete scar removal should not be promised.</p><div class="note">عدد الجلسات ونوعها والفاصل بينها لا يمكن تحديده بدقة قبل فحص نوع الندبات، الجلد وحب الشباب النشط.</div>',1)
s=rep(s,'<section class="card"><h2>ما الذي نعرف أنه متاح في عيادات أوسارا؟</h2><p>الموقع الحالي يذكر بالفعل خدمات الديرمابن/الميكرونيدلينغ والتقشير الكيميائي وPRP ضمن خدمات العيادة. أما السبسجن وTCA CROSS وتقنيات إعادة التسطيح الأخرى، فيتم ذكرها هنا كخيارات علاج عامة يجب مناقشة ملاءمتها وتوافرها أثناء الاستشارة بدلاً من افتراض توفرها تلقائياً.</p></section>','<section class="card"><h2>ما الذي نعرف أنه متاح في عيادات أوسارا؟</h2><p>الموقع الحالي يذكر بالفعل خدمات الديرمابن/الميكرونيدلينغ والتقشير الكيميائي وPRP ضمن خدمات العيادة. أما السبسجن وTCA CROSS وتقنيات إعادة التسطيح الأخرى، فيتم ذكرها هنا كخيارات علاج عامة يجب مناقشة ملاءمتها وتوافرها أثناء الاستشارة بدلاً من افتراض توفرها تلقائياً.</p><p class="en">The current site already lists Dermapen/microneedling, chemical peels and PRP among clinic services. Subcision, TCA CROSS and other resurfacing approaches are described here as general options whose suitability and availability should be confirmed during consultation.</p></section>','acne availability English')
s=s.replace('</a> إذا كان بحثك عن حالة جلدية مزمنة أخرى.</p><div class="cta-row">','</a> إذا كان بحثك عن حالة جلدية مزمنة أخرى.</p><p class="en">Consultation includes scar classification, assessment of active acne and pigmentation risk, and discussion of a realistic staged plan.</p><div class="cta-row">',1)
p.write_text(s)

# Make the four PR2 review entries quote actual page wording rather than summaries.
p=Path('MEDICAL_REVIEW_REQUIRED.md'); s=p.read_text()
old='''| `/psoriasis-treatment` | “Some patients may also develop joint symptoms that warrant assessment.” | Psoriasis overview | Association with psoriatic arthritis is appropriate but wording should be physician-reviewed for scope and escalation. |\n| `/psoriasis-treatment` | “Seek urgent medical assessment if psoriasis becomes very widespread, intensely red/painful, or widespread pustules occur with fever or systemic illness.” | Urgent assessment section | Escalation language should be physician-reviewed for severity thresholds and local care pathways. |\n| `/acne-scar-treatment` | “Subcision may be considered for some rolling or tethered depressed scars; TCA CROSS may be discussed for selected deeper narrow scars.” | Treatment-options section | Procedure-to-scar matching is medically specific and should be physician-reviewed; page does not claim these procedures are available at OSara Clinics. |\n| `/acne-scar-treatment` | “Many cases require multiple sessions and may benefit from a staged combination plan.” | Expectations section | General treatment-course statement should be physician-reviewed and kept free of guaranteed outcomes. |'''
new='''| `/psoriasis-treatment` | “الألم أو التيبس أو التورم في المفاصل يجب ذكره للطبيب.” | When to see a dermatologist | Association with psoriatic arthritis is appropriate but wording should be physician-reviewed for scope and escalation. |\n| `/psoriasis-treatment` | “اطلب تقييماً طبياً عاجلاً إذا أصبحت الصدفية واسعة جداً أو شديدة الاحمرار والألم، ظهرت بثرات منتشرة مع حرارة أو شعور عام بالتعب، حدث تدهور سريع، أو ظهرت أعراض مفصلية شديدة.” | Urgent assessment section | Escalation language should be physician-reviewed for severity thresholds and local care pathways. |\n| `/acne-scar-treatment` | “Subcision | السبسجن — تحرير الأشرطة الليفية تحت بعض الندبات المنخفضة، خصوصاً الندبات المتدحرجة أو الملتصقة.” and “TCA CROSS — تطبيق موضعي ومحدد... داخل بعض الندبات الضامرة...” | Treatment-options section | Procedure-to-scar matching is medically specific and should be physician-reviewed; page does not claim these procedures are available at OSara Clinics. |\n| `/acne-scar-treatment` | “كثير من الحالات تحتاج عدة جلسات، وقد تكون النتيجة الأفضل مع خطة مركبة ومتدرجة بحسب الاستجابة.” | Expectations section | General treatment-course statement should be physician-reviewed and kept free of guaranteed outcomes. |'''
if old not in s: raise SystemExit('review rows not found')
s=s.replace(old,new,1); p.write_text(s)
