import fs from 'fs'; import { chromium } from 'playwright';
const BASE='https://osaraclinics.com';
const ROUTES=['/','/dermatology','/ophthalmology','/doctors/dr-osama-alwreikat','/doctors/dr-sara-abu-touq','/psoriasis-treatment','/acne-scar-treatment','/vitiligo-jordan','/mole-removal','/school-health','/botox-hyperhidrosis'];
const SHOTS=['/dermatology','/ophthalmology','/doctors/dr-osama-alwreikat','/doctors/dr-sara-abu-touq'];
const refs=['/','/vitiligo-jordan','/mole-removal','/school-health']; const repaired=['/dermatology','/ophthalmology','/doctors/dr-osama-alwreikat','/doctors/dr-sara-abu-touq','/psoriasis-treatment','/acne-scar-treatment'];
fs.mkdirSync('pr4-prod-screenshots',{recursive:true}); const browser=await chromium.launch({headless:true}); const ctx=await browser.newContext({viewport:{width:390,height:844}}); let errors=[]; let report={pages:{},events:{},ga4:{},visual:{}};
async function inspect(route){ const p=await ctx.newPage(); let consoleErrors=[]; p.on('console',m=>{if(m.type()==='error') consoleErrors.push(m.text())}); p.on('pageerror',e=>consoleErrors.push(String(e))); const resp=await p.goto(BASE+route,{waitUntil:'networkidle',timeout:60000}); const d=await p.evaluate(()=>({sw:document.documentElement.scrollWidth,bw:document.body.scrollWidth,iw:innerWidth,h1:document.querySelectorAll('h1').length,broken:[...document.images].filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.src),css:[...document.querySelectorAll('link[rel=stylesheet]')].map(x=>x.href)})); if(!resp||resp.status()!==200) errors.push(`${route} browser status ${resp?.status()}`); if(d.sw>d.iw||d.bw>d.iw) errors.push(`${route} overflow ${d.sw}/${d.bw}/${d.iw}`); if(d.broken.length) errors.push(`${route} broken images`); if(consoleErrors.length) errors.push(`${route} console ${consoleErrors.join(' | ')}`); report.pages[route]={...d,consoleErrors}; if(SHOTS.includes(route)) await p.screenshot({path:`pr4-prod-screenshots/${route.replaceAll('/','_').replace(/^_/,'')}.png`,fullPage:true}); await p.close(); }
for(const r of ROUTES) await inspect(r);
for(const r of repaired){ if(!report.pages[r].css.some(x=>x.includes('/assets/guide-layout.css'))) errors.push(`${r} missing guide-layout.css`); }
for(const r of refs){ if(report.pages[r].css.some(x=>x.includes('/assets/guide-layout.css'))) errors.push(`${r} unexpectedly loads guide-layout.css`); }
// Verify GA4 page_view reaches Google from production and custom events exactly once by intercepting collect requests.
async function collect(route, selector, expected){ const p=await ctx.newPage(); let hits=[]; p.on('request',req=>{ const u=req.url(); if(/google-analytics\.com\/g\/collect|region1\.google-analytics\.com\/g\/collect/.test(u)) hits.push(u); }); await p.goto(BASE+route,{waitUntil:'networkidle',timeout:60000}); await p.waitForTimeout(1500); const pageViews=hits.filter(u=>decodeURIComponent(u).includes('en=page_view')); if(pageViews.length<1) errors.push(`${route} no GA4 page_view network hit`); report.ga4[route]={page_view_hits:pageViews.length,total_collect:hits.length}; if(selector){ hits=[]; const loc= p.locator(selector).first(); await loc.click({noWaitAfter:true}); await p.waitForTimeout(1200); const eventHits=hits.filter(u=>decodeURIComponent(u).includes(`en=${expected}`)); if(eventHits.length!==1) errors.push(`${expected} count ${eventHits.length}`); report.events[expected]=eventHits.length; } await p.close(); }
await collect('/dermatology','[data-appointment]','appointment_click');
await collect('/dermatology','.whatsapp-float','whatsapp_click');
await collect('/ophthalmology','a[href^="tel:"]','phone_click');
await collect('/ophthalmology','a[href*="google.com/maps"]','directions_click');
// Meta Pixel presence in DOM/runtime.
const mp=await ctx.newPage(); await mp.goto(BASE+'/',{waitUntil:'networkidle',timeout:60000}); const meta=await mp.evaluate(()=>({fbq:typeof window.fbq==='function',pixel:[...document.scripts].some(s=>s.src.includes('connect.facebook.net'))})); report.meta_pixel=meta; if(!meta.fbq||!meta.pixel) errors.push('Meta Pixel missing'); await mp.close();
report.visual={reference_pages:refs,repaired_pages:repaired,screenshots:SHOTS}; report.errors=errors; fs.writeFileSync('pr4-prod-browser.json',JSON.stringify(report,null,2)); console.log(JSON.stringify(report,null,2)); await browser.close(); process.exit(errors.length?1:0);