import fs from 'fs'; import { chromium } from 'playwright';
const BASE='https://osaraclinics.com';
const ROUTES=['/','/dermatology','/ophthalmology','/doctors/dr-osama-alwreikat','/doctors/dr-sara-abu-touq','/psoriasis-treatment','/acne-scar-treatment','/vitiligo-jordan','/mole-removal','/school-health','/botox-hyperhidrosis'];
const SHOTS=['/dermatology','/ophthalmology','/doctors/dr-osama-alwreikat','/doctors/dr-sara-abu-touq'];
const refs=['/','/vitiligo-jordan','/mole-removal','/school-health']; const repaired=['/dermatology','/ophthalmology','/doctors/dr-osama-alwreikat','/doctors/dr-sara-abu-touq','/psoriasis-treatment','/acne-scar-treatment'];
fs.mkdirSync('pr4-prod-screenshots',{recursive:true}); const browser=await chromium.launch({headless:true}); const ctx=await browser.newContext({viewport:{width:390,height:844}}); let errors=[]; let report={pages:{},events:{},ga4:{},visual:{}};
async function inspect(route){ const p=await ctx.newPage(); let consoleErrors=[]; p.on('console',m=>{if(m.type()==='error') consoleErrors.push(m.text())}); p.on('pageerror',e=>consoleErrors.push(String(e))); const resp=await p.goto(BASE+route,{waitUntil:'networkidle',timeout:60000}); const d=await p.evaluate(()=>({sw:document.documentElement.scrollWidth,bw:document.body.scrollWidth,iw:innerWidth,h1:document.querySelectorAll('h1').length,broken:[...document.images].filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.src),css:[...document.querySelectorAll('link[rel=stylesheet]')].map(x=>x.href)})); if(!resp||resp.status()!==200) errors.push(`${route} browser status ${resp?.status()}`); if(d.sw>d.iw||d.bw>d.iw) errors.push(`${route} overflow ${d.sw}/${d.bw}/${d.iw}`); if(d.broken.length) errors.push(`${route} broken images`); if(consoleErrors.length) errors.push(`${route} console ${consoleErrors.join(' | ')}`); report.pages[route]={...d,consoleErrors}; if(SHOTS.includes(route)) await p.screenshot({path:`pr4-prod-screenshots/${route.replaceAll('/','_').replace(/^_/,'')}.png`,fullPage:true}); await p.close(); }
for(const r of ROUTES) await inspect(r);
for(const r of repaired){ if(!report.pages[r].css.some(x=>x.includes('/assets/guide-layout.css'))) errors.push(`${r} missing guide-layout.css`); }
for(const r of refs){ if(report.pages[r].css.some(x=>x.includes('/assets/guide-layout.css'))) errors.push(`${r} unexpectedly loads guide-layout.css`); }
async function verifyGA(route,selector,expected){ const p=await ctx.newPage(); await p.addInitScript(()=>{ window.__gaCalls=[]; Object.defineProperty(window,'dataLayer',{configurable:true,get(){return this.__dl||(this.__dl=[]);},set(v){this.__dl=v; const orig=v.push.bind(v); v.push=(...args)=>{ try{ if(args[0]&&typeof args[0]==='object'&&typeof args[0].length==='number') window.__gaCalls.push(Array.from(args[0])); }catch(e){} return orig(...args); }; }}); }); let loader=false; p.on('request',req=>{if(req.url().includes('googletagmanager.com/gtag/js?id=G-72BY7LC2V2')) loader=true;}); await p.goto(BASE+route,{waitUntil:'networkidle',timeout:60000}); await p.waitForTimeout(1000); const before=await p.evaluate(()=>({gtag:typeof window.gtag==='function',calls:window.__gaCalls||[],dl:(window.dataLayer||[]).map(x=>{try{return Array.from(x)}catch(e){return x}})})); const allBefore=[...before.calls,...before.dl]; const configCount=allBefore.filter(x=>Array.isArray(x)&&x[0]==='config'&&x[1]==='G-72BY7LC2V2').length; if(!loader||!before.gtag||configCount<1) errors.push(`${route} GA4 loader/config inactive`); report.ga4[route]={loader,gtag:before.gtag,config_count:configCount,page_view_dispatch:'implicit via gtag config send_page_view'}; if(selector){ await p.locator(selector).first().click({noWaitAfter:true}); await p.waitForTimeout(500); const after=await p.evaluate(()=>({calls:window.__gaCalls||[],dl:(window.dataLayer||[]).map(x=>{try{return Array.from(x)}catch(e){return x}})})); const all=[...after.calls,...after.dl]; const cnt=all.filter(x=>Array.isArray(x)&&x[0]==='event'&&x[1]===expected).length; report.events[expected]=cnt; if(cnt!==1) errors.push(`${expected} gtag invocation count ${cnt}`); } await p.close(); }
await verifyGA('/dermatology','[data-appointment]','appointment_click');
await verifyGA('/dermatology','.whatsapp-float','whatsapp_click');
await verifyGA('/ophthalmology','a[href^="tel:"]','phone_click');
await verifyGA('/ophthalmology','a[href*="google.com/maps"]','directions_click');
const mp=await ctx.newPage(); await mp.goto(BASE+'/',{waitUntil:'networkidle',timeout:60000}); const meta=await mp.evaluate(()=>({fbq:typeof window.fbq==='function',pixel:[...document.scripts].some(s=>s.src.includes('connect.facebook.net'))})); report.meta_pixel=meta; if(!meta.fbq||!meta.pixel) errors.push('Meta Pixel missing'); await mp.close(); report.visual={reference_pages:refs,repaired_pages:repaired,screenshots:SHOTS}; report.errors=errors; fs.writeFileSync('pr4-prod-browser.json',JSON.stringify(report,null,2)); console.log(JSON.stringify(report,null,2)); await browser.close(); process.exit(errors.length?1:0);