import fs from 'fs';
import { chromium } from 'playwright';
const PRE='https://deploy-preview-5--gregarious-malabi-0dc7e1.netlify.app';
const PROD='https://osaraclinics.com';
const MAP='https://maps.app.goo.gl/FMrYnf8xmhJJETsG9?g_st=ac';
const ROUTES=['/','/dermatology','/ophthalmology','/doctors/dr-osama-alwreikat','/doctors/dr-sara-abu-touq','/psoriasis-treatment','/acne-scar-treatment','/vitiligo-jordan','/mole-removal','/school-health','/botox-hyperhidrosis'];
fs.mkdirSync('pr5-screenshots',{recursive:true});
const browser=await chromium.launch({headless:true}); const ctx=await browser.newContext({viewport:{width:390,height:844}});
let errors=[]; let report={pages:{},events:{},analytics:{},screenshots:[]};
async function inspect(route){const p=await ctx.newPage(); let ce=[]; p.on('console',m=>{if(m.type()==='error')ce.push(m.text())}); p.on('pageerror',e=>ce.push(String(e))); const resp=await p.goto(PRE+route,{waitUntil:'networkidle',timeout:60000}); const d=await p.evaluate(()=>({sw:document.documentElement.scrollWidth,bw:document.body.scrollWidth,iw:innerWidth,h1:document.querySelectorAll('h1').length,broken:[...document.images].filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.src),cta:[...document.querySelectorAll('.osara-contact-btn')].map(a=>({text:a.textContent.trim(),href:a.href,rect:a.getBoundingClientRect().toJSON()}))})); if(!resp||resp.status()!=200)errors.push(`${route} browser status`); if(d.sw>d.iw||d.bw>d.iw)errors.push(`${route} overflow ${d.sw}/${d.bw}/${d.iw}`); if(d.broken.length)errors.push(`${route} broken image`); if(ce.length)errors.push(`${route} console ${ce.join('|')}`); if(route!=='/'&&d.cta.length<3)errors.push(`${route} missing standardized CTA group`); report.pages[route]={...d,consoleErrors:ce}; await p.close();}
for(const r of ROUTES) await inspect(r);
async function shot(base,route,selector,name){const p=await ctx.newPage();await p.goto(base+route,{waitUntil:'networkidle',timeout:60000});const loc=p.locator(selector).first();if(await loc.count())await loc.screenshot({path:`pr5-screenshots/${name}.png`});else{errors.push(`screenshot selector missing ${base}${route} ${selector}`);await p.screenshot({path:`pr5-screenshots/${name}.png`,fullPage:true});}report.screenshots.push(name);await p.close();}
await shot(PROD,'/','.location-grid','before-home-location'); await shot(PRE,'/','.location-grid','after-home-location');
await shot(PROD,'/dermatology','.footer','before-dermatology-contact'); await shot(PRE,'/dermatology','.osara-contact-block','after-dermatology-contact');
await shot(PROD,'/doctors/dr-osama-alwreikat','.footer','before-doctor-contact'); await shot(PRE,'/doctors/dr-osama-alwreikat','.osara-contact-block','after-doctor-contact');
// Exact-once analytics via wrapping gtag after page load.
async function eventProbe(route,selector,eventName){const p=await ctx.newPage();await p.goto(PRE+route,{waitUntil:'networkidle',timeout:60000});await p.evaluate(()=>{window.__calls=[];const orig=window.gtag;window.gtag=function(){window.__calls.push(Array.from(arguments));return orig.apply(this,arguments)}});const loc=p.locator(selector).first();if(!(await loc.count())){errors.push(`${eventName} selector missing`);await p.close();return;}const href=await loc.getAttribute('href');if(eventName==='directions_click'&&href!==MAP)errors.push(`directions href ${href}`);await loc.click({noWaitAfter:true});await p.waitForTimeout(500);const calls=await p.evaluate((name)=>window.__calls.filter(c=>c[0]==='event'&&c[1]===name),eventName);report.events[eventName]={count:calls.length,calls};if(calls.length!==1)errors.push(`${eventName} count ${calls.length}`);await p.close();}
await eventProbe('/dermatology','[data-appointment]','appointment_click');
await eventProbe('/dermatology','.osara-contact-wa','whatsapp_click');
await eventProbe('/ophthalmology','.osara-contact-call','phone_click');
await eventProbe('/ophthalmology','.osara-contact-directions','directions_click');
// GA4 + Meta Pixel remain active on preview homepage.
const p=await ctx.newPage();await p.goto(PRE+'/',{waitUntil:'networkidle',timeout:60000});report.analytics=await p.evaluate(()=>({gtag:typeof window.gtag==='function',gaLoader:[...document.scripts].some(s=>s.src.includes('googletagmanager.com/gtag/js?id=G-72BY7LC2V2')),gaConfig:(window.dataLayer||[]).filter(x=>x&&x[0]==='config'&&x[1]==='G-72BY7LC2V2').length,fbq:typeof window.fbq==='function',pixel:[...document.scripts].some(s=>s.src.includes('connect.facebook.net'))}));if(!report.analytics.gtag||!report.analytics.gaLoader||report.analytics.gaConfig<1)errors.push('GA4 inactive');if(!report.analytics.fbq||!report.analytics.pixel)errors.push('Meta Pixel inactive');
// Homepage no longer has map iframe; focus is fixed card.
const mapState=await p.evaluate(()=>({mapIframes:[...document.querySelectorAll('iframe')].filter(i=>/maps/i.test(i.src)).length,staticCard:!!document.querySelector('.map-static-card'),dir:document.querySelector('.map-static-card .osara-contact-directions')?.href}));report.homeMap=mapState;if(mapState.mapIframes!==0||!mapState.staticCard||mapState.dir!==MAP)errors.push('homepage map focus implementation');await p.close();
report.errors=errors;fs.writeFileSync('pr5-browser.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();process.exit(errors.length?1:0);
